version: "3.7"

services:
  db:
    image: postgres:latest
    volumes:
      - ./dbdata/postgres:/var/lib/postgresql/data
    env_file: ./.env.local
    ports:
      - "5432:5432"

volumes:
  postgre_data:
    driver: local
