[package]
name = "ark_executor"
version = "0.1.0"

[dependencies]
starknet = ">=2.1.0"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.4.1" }

[[target.starknet-contract]]
sierra = true
casm = true

[lib]
